repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 0225754079df7cc99525ead1decb5a8e92ecb158 #v0.1.25
    hooks:
      - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev:  37d3055fece566105cf8cff7c17b7b2355a01677 #v1.14.2
    hooks:
      - id: helm-docs-container
        args:
          - --chart-search-root=sample-service/timer-api
