apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.resources }}
          resources:
            {{- if .Values.resources.limits }}
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            {{- end }}
            {{- if .Values.resources.requests }}
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            {{- end }}
          {{- end }}
          env:
            {{- range .Values.env }}
              - name: {{ .name }}
                value: {{ .value }}
            {{- end }}
            {{- range .Values.secretEnv }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName | quote }}
                  key: {{ .key | quote }}
            {{- end }}
          volumeMounts:
            {{- range .Values.secrets }}
            - name: {{ .volumeName }}
              mountPath: /etc/secrets/{{ .fileName }}
              subPath: {{ .fileName }}
              readOnly: true
            {{- end }}
      volumes:
        {{- range .Values.secrets }}
        - name: {{ .volumeName }}
          secret:
            secretName: {{ .secretName | quote }}
            items:
              - key: {{ .key | quote }}
                path: {{ .fileName | quote }}
        {{- end }}
