kube-prometheus-stack:
  grafana:
    adminPassword: "admin"
    service:
      type: NodePort
      nodePort: 32000
  prometheus:
    prometheusSpec:
      retention: 1d

loki-stack:
  loki:
    enabled: true
  promtail:
    enabled: true
